backend:
  name: git-gateway
  branch: main

media_folder: "images"
public_folder: "/images"

collections:
  - name: "blog"
    label: "Blog"
    files:
      - name: "posts"
        label: "All Posts"
        file: "posts/index.json"
        fields:
          - name: "posts"
            label: "Posts"
            widget: "list"
            fields:
              - { label: "Title",    name: "title",    widget: "string" }
              - { label: "Date",     name: "date",     widget: "datetime" }
              - { label: "Category", name: "category", widget: "string",   required: false }
              - { label: "Excerpt",  name: "excerpt",  widget: "text",     required: false }
              - { label: "Body",     name: "body",     widget: "markdown" }